name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_41140025
          password: Sakthi10122004
          port: 21
          server-dir: autoexamcell.gt.tc/htdocs/
